--
-- CUP_BIT_CALCULO_CUP  (Synonym) 
--

CREATE OR REPLACE SYNONYM CUPAPP.CUP_BIT_CALCULO_CUP FOR CUPADM.CUP_BIT_CALCULO_CUP;

CREATE OR REPLACE SYNONYM CUPAPP.PKG_CUP_SP_HOMOLOGA_FECHA FOR CUPADM.PKG_CUP_SP_HOMOLOGA_FECHA